---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: cloudscale-slb-controller
  name: {{ .Release.Name }}-sa

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: cloudscale-slb-controller
  name: {{ .Release.Name }}-cr
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - get
      - create
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - services/status
    verbs:
      - update

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: cloudscale-slb-controller
  name: {{ .Release.Name }}-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-cr
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-sa
    namespace: {{ .Release.Namespace }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: cloudscale-slb-controller
  name: {{ .Release.Name }}-role
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - create
      - patch
      - update

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: cloudscale-slb-controller
  name: {{ .Release.Name }}-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-role
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-sa
